config/routes.rb
BillSplitting::Application.routes.draw do
  resources :expences do
    collection do
      get "load_users"
    end
  end

  resources :user_groups

  resources :users
  
  resources :groups

  root :to => 'users#index'

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base

  belongs_to :user
  belongs_to :group
  
  validates :user_id, :group_id, presence: true
  attr_accessible :user_id, :group_id
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_groups }
    end
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_group }
    end
  end

  # GET /user_groups/new
  # GET /user_groups/new.json
  def new
    @user_group = UserGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_group }
    end
  end

  # GET /user_groups/1/edit
  def edit
    @user_group = UserGroup.find(params[:id])
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
    @user_ids = params[:user_group][:user_id].drop(1) if !params[:user_group][:user_id].blank?
    @create_obj = []
    @user_ids.each do |id|
       @create_obj << {:group_id=>params[:user_group][:group_id], :user_id=>id}
     end  
    @user_group = UserGroup.create(@create_obj)
    respond_to do |format|
      if !@user_group.blank?
        format.html { redirect_to :action=>"index", notice: 'User group was successfully created.' }
        format.json { render json: @user_group, status: :created, location: @user_group }
      else
        format.html { render action: "new" }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_groups/1
  # PUT /user_groups/1.json
  def update
    @user_group = UserGroup.where(group_id:params[:user_group][:group_id])
    @user_group.destroy_all
    @user_ids = params[:user_group][:user_id].drop(1) if !params[:user_group][:user_id].blank?
    @create_obj = []
    @user_ids.each do |id|
       @create_obj << {:group_id=>params[:user_group][:group_id], :user_id=>id}
     end  
    @user_group = UserGroup.create(@create_obj)
    respond_to do |format|
      if !@user_group.blank?
        format.html { redirect_to :action=>"index", notice: 'User group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group = UserGroup.find(params[:id])
    @user_group.destroy

    respond_to do |format|
      format.html { redirect_to user_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.collection_select(:group_id, Group.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select(:group_id, User.all, :id, :name, {}, {multiple:true}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing User Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<h1>Listing User Groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_groups.each do |user_group| %>
  <tr>
    <td><%= user_group.group.name %></td>
    <td><%= link_to 'Show', user_group %></td>
    <td><%= link_to 'Edit', edit_user_group_path(user_group) %></td>
    <td><%= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User group', new_user_group_path %>

app/views/user_groups/new.html.erb
<h1>New User Group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user_group.name %>
</p>

<p>
  <b>User:</b>
  <%= @user_group.user_id %>
</p>


<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>