config/routes.rb
BillSplitting::Application.routes.draw do
  resources :expences do
    collection do
      get "load_users"
    end
  end

  resources :user_groups

  resources :users
  
  resources :groups

  root :to => 'users#index'

end

app/models/expence.rb
class Expence < ActiveRecord::Base
  
  belongs_to :group
  belongs_to :user
  has_many :expences_details
  
  serialize :user_ids
  
  validates :amount, :description, :group_id, :location, presence: true
  
  attr_accessible :amount, :description, :group_id, :location, :user_ids
end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :expences
 
  attr_accessible :name, :description
  
  validates :name, presence: true
  validates :description, length: {
    maximum: 250,
    tokenizer: lambda { |str| str.scan(/\w+/) },
    too_long: "must have at most %{count} words"
  }
end

app/controllers/expences_controller.rb
class ExpencesController < ApplicationController
  # GET /expences
  # GET /expences.json
  def index
    @expences = Expence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expences }
    end
  end

  # GET /expences/1
  # GET /expences/1.json
  def show
    @expence = Expence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expence }
    end
  end

  # GET /expences/new
  # GET /expences/new.json
  def new
    @expence = Expence.new
    @users = []
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expence }
    end
  end

  # GET /expences/1/edit
  def edit
    @expence = Expence.find(params[:id])
  end

  # POST /expences
  # POST /expences.json
  def create
    @expence = Expence.new(params[:expence])
    user_keys = params[:expences].keys
    user_values = params[:expences].values
    amount_values = params[:amount].values
    
    respond_to do |format|
      if @expence.save
        user_keys.each_with_index do |key, ind|
          ExpencesDetail.create(:user_id=>key.split("_")[1], :expence_id=>@expence.id, :amount=>amount_values[ind]) if user_values[ind]=="1"  
        end
        format.html { redirect_to @expence, notice: 'Expence was successfully created.' }
        format.json { render json: @expence, status: :created, location: @expence }
      else
        format.html { render action: "new" }
        format.json { render json: @expence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expences/1
  # PUT /expences/1.json
  def update
    @expence = Expence.find(params[:id])

    respond_to do |format|
      if @expence.update_attributes(params[:expence])
        format.html { redirect_to @expence, notice: 'Expence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expences/1
  # DELETE /expences/1.json
  def destroy
    @expence = Expence.find(params[:id])
    @expence.destroy

    respond_to do |format|
      format.html { redirect_to expences_url }
      format.json { head :no_content }
    end
  end
  
  def load_users
    @users = User.where("id in (?)", UserGroup.where(:group_id=>params[:id]).pluck(:user_id))
    
    respond_to do |format|
      format.html { render :partial => "load_users" }
    end
  end
end

app/helpers/expences_helper.rb
module ExpencesHelper

def user_name_list(expence)  
  User.where(:id=>ExpencesDetail.where(:expence_id=>expence.id).pluck(:user_id)).pluck(:name).join(", ")
end

def user_amount(expence_id, user_id)
  ExpencesDetail.where(:expence_id=>expence_id, :user_id => user_id).first.amount
end

def user_list(expence_id)
  User.where(:id=>ExpencesDetail.where(:expence_id=>expence_id).pluck(:user_id))
end

def total_expence(group_id)
  sum = 0.0
  amount = Expence.where(:group_id=>group_id).pluck(:amount)
  return amount.inject(:+)
end

def user_spent(user_id)
  amount = ExpencesDetail.where(:user_id=> user_id).pluck(:amount)
  return amount.inject(:+)
end

def user_deference(user)
  amount = user_spent(user.id).to_f
  needs_to_pay = 0.0
  Expence.where(:group_id=>1).each do |e|
    needs_to_pay += (e.amount/e.expences_details.count) if e.expences_details.pluck(:user_id).include?(user.id)
  end
  return (amount - needs_to_pay)
end
  
end

app/views/expences/_form.html.erb
<%= form_for(@expence) do |f| %>
  <% if @expence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expence.errors.count, "error") %> prohibited this expence from being saved:</h2>

      <ul>
      <% @expence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.collection_select(:group_id, Group.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :user_ids %><br />
    <div id="user_list">
      <%= render :partial=>"load_users" %>	
    </div>	
  </div>
  <div class="field">
    <%= f.label :amount, "Total Amount" %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expences/_load_users.html.erb
<% @users.each do |user| %>
  <%= check_box :expences, "user_"+user.id.to_s, {:onclick=>"onSelectUser(this);"} %><%= user.name %>
  <%= text_field :amount, "user_"+user.id.to_s, :disabled=>"disabled" %>
  <br /><br />	 
<% end %>

app/views/expences/edit.html.erb
<h1>Editing expence</h1>

<%= render 'form' %>

<%= link_to 'Show', @expence %> |
<%= link_to 'Back', expences_path %>

app/views/expences/index.html.erb
<h1>Listing expences</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Group</th>
    <th>Location</th>
    <th>Total Amount</th>
    <th>User ids</th>
    <th></th>
  </tr>

<% @expences.each do |expence| %>
  <tr>
    <td><%= expence.description %></td>
    <td><%= expence.group.name %></td>
    <td><%= expence.location %></td>
    <td><%= expence.amount %></td>
    <td><%= user_name_list(expence) %></td>
    <td><%= link_to 'Show', expence %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expence', new_expence_path %>

<br /><br />

<div>
  Total Expences = <b><%= total_expence(1) %></b>	
  <table cellpadding="6" cellspacing="6" border="">
    <thead>
      <tr>
      	<th>Name</th>
      	<th>Total Spent</th>
      	<th>Difference</th>
      </tr>	
    </thead>
    <tbody>
      <% Group.find(1).users.each do | user | %>
        <tr>
      	  <td><%= user.name %></td>
      	  <td><%= user_spent(user.id) %></td>
      	  <td>
      	  	<%= user_deference(user) %>
      	  </td>
        </tr>
      <% end %>  	
    </tbody>
  </table>  		
</div>	

app/views/expences/new.html.erb
<h1>New expence</h1>

<%= render 'form' %>

<%= link_to 'Back', expences_path %>

app/views/expences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @expence.description %>
</p>

<p>
  <b>Group:</b>
  <%= @expence.group.name %>
</p>

<p>
  <b>Location:</b>
  <%= @expence.location %>
</p>

<p>
  <b>Amount:</b>
  <%= @expence.amount %>
</p>

<p>
  <b>Users :</b>
  <% user_list(@expence).each_with_index do |user| %>
    <%= user.name + "-" + user_amount(@expence.id, user.id).to_s %>
  <% end %>
</p>


<%= link_to 'Edit', edit_expence_path(@expence) %> |
<%= link_to 'Back', expences_path %>